default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: xiaoxing0824

development:
  <<: *default
  database: encore_development
  host: localhost
  pool: 10

test:
  <<: *default
  database: encore_test
  host: localhost
  pool: 10

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['WEB_MAX_THREADS'] || 5 %>